### ISSUE TITLE
Build Your First REST API with Node.js and Express 🚀

### ISSUE THREAD

**Issue by nunyvega** [ByteBiteChef/ByteBiteChef.github.io#10]
## Objective
Max, it's time to put your newly MySQL skills into practice and venture into backend development! You will build a REST API using Node.js and Express, and later integrate it with a frontend interface. This project will be broken down into clear steps to help you grasp each concept thoroughly.

#### Step 1: Complete the Node.js and Express Tutorial 📚
- Watch the tutorial ["Build a REST API with Node JS and Express | CRUD API Tutorial"](https://www.youtube.com/watch?v=l8WPWK9mS5M) on YouTube.
- In this 1-hour video, you'll learn how to create a simple API and test it using Postman.
- Initially, you'll mock a database using a JSON file.
- [x] Mark this task item when completed

#### Step 2: Document and Comment Your Code 📝
- Once you have the server working, go through your code and add comments to each part of your code.
- Each comment should clearly explain what a particular piece of code does.
- This will help reinforce your understanding and serve as documentation.
- [x] Mark this task item when completed

##### Step 3: Build a Frontend Interface 🔗
- Create a frontend where you can interact with your API.
- Use Bootstrap to style your frontend for a clean and user-friendly interface.
- Implement functionalities to display, add, update, and delete data through the API (CRUD).
- [x] Mark this task item when completed

##### Step 4: Transition to a Real Database with SQLite 🗃️
- Set up a [SQLite database](https://www.sqlite.org/index.html).
- Modify your API to interact with the SQLite database instead of the JSON file.
- Ensure all CRUD functionalities are working with the new database.
- [x] Mark this task item when completed

#### Notes 📝
- Remember to take your time with the tutorial and understand each concept.
- Testing your API with Postman is crucial to ensure it's working correctly.
- Frequent commits with clear messages are important, especially when transitioning to a real database.
- Feel free to ask questions or seek help whenever you're unsure.

---

Max, this project is a big step into full-stack development, and I'm confident you'll handle it brilliantly. Looking forward to seeing your REST API in action and how you integrate it with a frontend interface! Happy coding! 🌟💻

**Comment by ByteBiteChef** [comment]
Hello! Thanks for the new project, I'm going to start right away. 
Cheers!

**Comment by nunyvega** [comment]
how is it going @ByteBiteChef ?

**Comment by ByteBiteChef** [comment]
Hi, I finished step 2 and now, I'm working on the front end of the project using ChatGPT to clear some doubts.  I'll let you know how it goes. 

Thanks!

**Comment by ByteBiteChef** [comment]
Hello, I finished the last task on the list. I'm very happy with the results.

Thaks!

**Comment by nunyvega** [comment]
@ByteBiteChef whenever you have some minutes, can you please share shortly:

1. the tricky parts of this project for you, and how you got to complete those parts
2 add a link/screenshots to the final result
3. what would be your next steps if you had more time to complete this
4. what would you do differently if you start again

**Comment by ByteBiteChef** [comment]
The most difficult part of the project was to create all the controllers for the CRUD operations, everything was new to me. After that, I had a few challenges too, like creating an "async function" which was a concept that I knew already, but was still a bit complicated. 
Here is how my app looks.
<img width="1157" alt="Screenshot 2023-12-22 at 12 00 44" src="https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/144017722/4043da1b-5327-41ec-b94e-ba552bc33988">
 And, here is a part of the code:
<img width="706" alt="Screenshot 2023-12-22 at 12 02 30" src="https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/144017722/45a582d8-e6aa-43b7-b710-00cbe4bb7979">

The tutorial HOW TO BUILD A REST API helped me a lot to achieve my goals in this project.

To reinforce my understanding of fetch functions I use those videos:
https://www.youtube.com/watch?v=ccX3ApO4qz8&t=1675s
https://www.youtube.com/watch?v=KiRKUTDYlG8&t=928s&ab_channel=DearProgrammer

Using GPT was very helpful too.

In case I have more time to dedicate to this project I would like to work on the styling of the application but also, I would try to do a cleaner code. Besides that, I am happy with the results as I said.

If I had to start again I would spend more time on the basic concept of the project, like trying to understand as much as possible about what the CRUD is and how it works. Having a better overview of this, the project would it be much fluid.
