### ISSUE TITLE
Upgrade Basic Calculator to Advanced Version 🖩

### ISSUE THREAD

**Issue by nunyvega** [ByteBiteChef/ByteBiteChef.github.io#9]
## Objective
Max, let's take your basic calculator to the next level! Your task is to create an advanced calculator similar to the MacBook calculator. This project will involve enhancing the design with Bootstrap and adding more functionalities. 

It should include the functionalities included in this calculator:
![Screenshot 2023-12-06 at 11 29 04](https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/16329583/0d92e58f-f645-4cbc-9f57-4f01a9f5ac9e)

### Step 1: Set Up the Advanced Calculator Layout 🏗
- [x] Create a new HTML file for the advanced calculator.
- [x] Use Bootstrap to help design a layout that resembles the MacBook calculator.

### Step 2: Implement Basic Calculator Functions ➕➖✖➗
- [x] Ensure that your calculator can perform basic operations: addition, subtraction, multiplication, and division.
- [x] The layout should include buttons for digits (0-9), operations (+, -, *, /), and an equal (=) button.
- [x] Implement a clear (C) button to reset the current operation.

##### Step 3: Additional Functionalities 🔢
- [x] Add extra functionalities for percentage calculation, sign change (±), and decimal point (.).
- [x] Implement the functionalities related to continuous calculation, like clicking on equal (=) after an addition to add the number again to the current result.

##### Step 4: Styling the Calculator with Bootstrap 🎨
- [x] Use Bootstrap components and utilities to style the calculator.
- [x] Aim for a neat and intuitive design. It should be user-friendly and aesthetically pleasing.

##### Step 5: Testing and Debugging 🐞
- [x] Thoroughly test all the functionalities of your advanced calculator.
- [x] Ensure it's responsive and works well on different devices and screen sizes.
- [x] Debug any issues or irregularities you encounter.

#### Notes 📝
- Focus on one functionality at a time to ensure everything works correctly before moving to the next.
- Regularly push your changes to GitHub, and don’t hesitate to ask for feedback or help.
- Remember, a clean and intuitive UI is key for a calculator app.
- For this project, feel free to focus on the design first and then move to the functionalities, in case you prefer to work in that order.

---

Max, this is a great opportunity to build on what you've already accomplished and to challenge yourself with more advanced features. Looking forward to seeing your advanced calculator in action! Happy coding! 🚀💻

**Comment by ByteBiteChef** [comment]
Hello, I just finished this project. It was fun and challenging! I had a hard time with the JS logic but I sorted it out.
You can try my Mac Calculator at the following link
https://bytebitechef.github.io/Calculator/mac-calculator.html

And, this is how it looks:
<img width="813" alt="Screenshot 2023-12-11 at 12 39 07" src="https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/144017722/d4d5a305-0572-4a10-9ab8-72830449ccab">

Thank you very much!

**Comment by nunyvega** [comment]
Great job! 

Once you're done with your SQL course and video tutorials, please move to your new project:
## [Build Your First REST API with Node.js and Express 🚀 #10](https://github.com/ByteBiteChef/ByteBiteChef.github.io/issues/10)
